source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

link_with ['Smuoy', 'Smuoy Mock', 'SmuoyTests']

pod 'AFNetworking', '~> 2.0'


link_with ['Smuoy Mock', 'SmuoyTests']

pod 'OHHTTPStubs', '~> 3.1'

